### ISSUE TITLE
[no-delete] Deprecate rule

### ISSUE THREAD

**Issue by RebeccaStevens** [jonaskello/eslint-plugin-ts-immutable#12]
The `no-delete` rule doesn't really offer anything anymore. `no-array-mutation` and `no-object-mutation` will detect use of delete statements.

**Comment by jonaskello** [comment]
Yes, this will reduce the number of rules.

**Comment by RebeccaStevens** [comment]
Removed rather than deprecated as project is still before 1.0 release.
