### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by jonaskello** [jonaskello/eslint-plugin-ts-immutable#17]
Continuing from [these comments](https://github.com/jonaskello/eslint-plugin-ts-immutable/pull/8#issuecomment-509609725).

The current name `eslint-plugin-ts-immutable` has some drawbacks:

* It's long
* It implies that the package is explicitly for ts, while many rules work with plain js.
* It implies the rules are only for immutability, while many rules are for fp style.

Some alternative names:

* `eslint-plugin-immutable-ts`
* `eslint-plugin-immutable-fp`
* `eslint-plugin-functional`

I like `eslint-plugin-functional` since it is shorter. My only concern is that some user might be looking only for immutability (for example for a redux store) while thinking anything named "fp" or "functional" is too complex for their needs.

**Comment by RebeccaStevens** [comment]
I'm thinking `eslint-plugin-functional` is probably the best option now.
The number of functional rules has continued to grow while the number of purely immutable rules has decreased (due to some merging).

**Comment by jonaskello** [comment]
@RebeccaStevens FYI, the package and repo are now named eslint-plugin-functional.
