### ISSUE TITLE
Deprecate ignore-prefix and ignore-suffix?

### ISSUE THREAD

**Issue by jonaskello** [jonaskello/eslint-plugin-ts-immutable#4]
Now that we have `ignore-pattern` perhaps it is a good time to deprecate `ignore-prefix` and `ignore-suffix`? Having a single option will simplify the code and docs. The only advantage I can see is that a prefix/suffix check might be faster than a regex check but probably not enough to be noticeable.

**Comment by RebeccaStevens** [comment]
The only reason I see to keep `ignore-prefix` and `ignore-suffix` around is that they are slightly easier to use.
Removing them won't really simplify the code much as they are each quite [small functions](https://github.com/jonaskello/eslint-plugin-ts-immutable/blob/8e4f2a2684e14c2334e6257528197f5965734527/src/common/ignore-options.ts#L198-L234) that are each only called once ([in the same place the check for `ignore-pattern` is called](https://github.com/jonaskello/eslint-plugin-ts-immutable/blob/8e4f2a2684e14c2334e6257528197f5965734527/src/common/ignore-options.ts#L162-L193)). Simplifying the docs would be nice though.

I don't really have a strong opinion either way on whether or not to keep them.

**Comment by jonaskello** [comment]
Yes, you're right, this was mainly an issue when I was doing the docs :-). Documenting 3 options when one would be enough seemed redundant. Regarding `ignorePrefix` I ran across something similar for the [`@typescript-eslint/no-unused-vars`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md) rule. I wanted to ignore function params starting with `_` (like tsc does). For that I needed to specify the option `argsIgnorePattern: "^_"`.

So I guess the following would work?

* To emulate `ignorePrefix`: `ignorePattern: "^prefixToIgnore"`. 
* To emulate `ignoreSuffix`: `ignorePattern: "suffixToIgnore$"`. 

If that works I would say it is simple enough and we can document that possibility under `ignorePattern` instead of having separate options.

**Comment by RebeccaStevens** [comment]
Not quite, `ignorePattern` uses regex matching under the hood but the pattern you supply it with is more of a minimatch pattern. The reason I implemented it as such is so that object member pattern matching could be easily done.

Thus
* To emulate `ignorePrefix`: `ignorePattern: "*prefixToIgnore"`.
* To emulate `ignoreSuffix`: `ignorePattern: "suffixToIgnore*"`.

I've just created a few tests (as well as some other improvements) for `ignorePattern` on PR #6.

Note: I was unable to use the [minimatch]() library to do the pattern matching as it is designed exclusively for file path matching. Because of this I implemented the pattern matching myself and thus it isn't very feature rich. Ideally we would want to switch over to an external library to do the pattern matching but I'm not aware of any that would work for our particular use case.

**Comment by jonaskello** [comment]
Aha so I thought `ignorePattern` took a regular expression. Is there a reason it was not done with regular expressions? I'm guessing simplified patterns but not sure? Perhaps we could switch to use regular expressions like in the  [`argsIgnorePattern`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md#argsignorepattern) option of `@typescript-eslint/no-unused-vars`? It would be a breaking change compared to tslint-immutable but I guess all config has to be ported anyway.

**Comment by RebeccaStevens** [comment]
The reason I implemented it with minimatch-like pattern matching was so accessor paths could more easily be matched against.

For example:
```ts
const m_foo = {
  bar: {
    baz: [1, 2, 3],
    m_baz: [1, 2, 3]
  }
} as const;
const foo = m_foo;

// ignorePattern: "m_*"
m_foo.bar = {}; // this is ok
m_foo.bar.baz[1] = 4; // this is not ok

// ignorePattern: "m_*.**"
m_foo.bar = {}; // this is ok
m_foo.bar.baz[1] = 4; // this is ok

// ignorePattern: "**.m_*"
m_foo.bar.baz[1] = 4; // this is not ok
foo.bar.m_baz[1] = 4; // this is ok

// ignorePattern: "**.m_*.**"
m_foo.bar.baz[1] = 4; // this is ok
foo.bar.m_baz[1] = 4; // this is ok
```

We could switch over to simply using regex pattern matching but I don't think the above examples can easily translate.

**Comment by RebeccaStevens** [comment]
The reason I implemented it with minimatch-like pattern matching was so accessor paths could more easily be matched against.

For example:
```ts
const m_foo = {
  bar: {
    baz: [1, 2, 3],
    m_baz: [1, 2, 3]
  }
} as const;
const foo = m_foo;

// "no-array-mutation":  ["error", { "ignorePattern": "m_*" }]
// "no-object-mutation": ["error", { "ignorePattern": "m_*" }]
m_foo.bar = {};            // ok
m_foo.bar.baz = [4, 5, 6]; // error


// "no-array-mutation":  ["error", { "ignorePattern: "m_*.**" }]
// "no-object-mutation": ["error", { "ignorePattern: "m_*.**" }]
m_foo.bar = {};       // ok
m_foo.bar.baz[1] = 4; // ok
foo.bar.m_baz[1] = 4; // error


// "no-array-mutation":  ["error", { "ignorePattern: "**.m_*" }]
// "no-object-mutation": ["error", { "ignorePattern: "**.m_*" }]
m_foo.bar.baz[1] = 4; // error
foo.bar.m_baz[1] = 4; // ok


// "no-array-mutation":  ["error", { "ignorePattern: "**.m_*.**" }]
// "no-object-mutation": ["error", { "ignorePattern: "**.m_*.**" }]
m_foo.bar.baz[1] = 4; // ok
foo.bar.m_baz[1] = 4; // ok
```

We could switch over to simply using regex pattern matching but I don't think the above examples can easily be translated.

This sort of pattern matching is nice for accessors but it doesn't really make sense for rules like `no-expression-statement`; regex pattern matching would make more sense there.

**Comment by jonaskello** [comment]
Well, easy and regex is not two words I usually relate so I think you are right about the translation :-). 

OTOH regex is very flexible and well documented so it has that going for it. I guess it's a trade-off between flexible and well documented, or easy for common cases. Perhaps we can document accessor path matching regexs like the ones above so ppl don't have to figure them out by themselves. Or we could use regexp only for some rules, however that may be confusing too.

**Comment by RebeccaStevens** [comment]
I've just been looking at how ignore-pattern is currently implemented and it's not passing all cases in the above examples. I believe the pattern matching itself is correct but what node is does the pattern matching on is not (e.g. in some cases pattern matching is being done on an AssignmentExpression node instead of the child MemberExpression node's object property).

Seems there are bugs in the current implementation, I think the best cause of action maybe to just strip it out and switch over to regex pattern matching. The minimatch-like pattern matching could be reintroduced in future if it is need/wanted.

**Comment by RebeccaStevens** [comment]
We could have it so there are two options `ignore-pattern` and `ignore-accessor-pattern`; where `ignore-pattern` does regex pattern matching against the top most node and is available for all rules that want the ability to ignore things, and `ignore-accessor-pattern` does minimatch-like pattern matching against the accessor and is available only for rules where it makes sense.

**Comment by RebeccaStevens** [comment]
Removed rather than deprecated as project is still before 1.0 release.
